=== ATHIRACM2003/WSD_CIA_2/WSD_CIA_2_LAB_EXAM/recipe.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="www.pqr.com/proj" xmlns="www.pqr.com/proj">
    <xs:element name="projects">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="project1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="name" type="xs:string"></xs:element>
                            <xs:element name="description" type="xs:string"></xs:element>
                            <xs:element name="year" type="xs:integer">
                            </xs:element>
                            <xs:element name="earnings" type="xs:integer">
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="project2">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="name" type="xs:string"></xs:element>
                            <xs:element name="description" type="xs:string"></xs:element>
                            <xs:element name="year" type="xs:integer">
                            </xs:element>
                            <xs:element name="earnings" type="xs:integer">
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="project3">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="name" type="xs:string"></xs:element>
                            <xs:element name="description" type="xs:string"></xs:element>
                            <xs:element name="year" type="xs:integer">
                            </xs:element>
                            <xs:element name="earnings" type="xs:integer">
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="project4">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="name" type="xs:string"></xs:element>
                            <xs:element name="description" type="xs:string"></xs:element>
                            <xs:element name="year" type="xs:integer">
                            </xs:element>
                            <xs:element name="earnings" type="xs:integer">
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== ATHIRACM2003/WSD_CIA_2/WSD_CIA_2_LAB_EXAM/recipe.xml
<?xml version="1.0" encoding="UTF-8"?>
<projects xmlns="www.pqr.com/proj" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="www.pqr.com/proj recipe.xsd">
    <project1>
        <name>Chilly Paneer</name>
        <description>A famous dish of north India.</description>
        <year>2020</year>
        <earnings>2000</earnings>
    </project1>
    <project2>
        <name>Chilly Potato</name>
        <description>A crispy and spicy dish.</description>
        <year>2022</year>
        <earnings>5000</earnings>
    </project2>
    <project3>
        <name>Chilly Chicken</name>
        <description>A dish that everyone loves in south India.</description>
        <year>2023</year>
        <earnings>3000</earnings>
    </project3>
    <project4>
        <name>Biriyani</name>
        <description>Lovable dish of India.</description>
        <year>2024</year>
        <earnings>5000</earnings>
    </project4>
</projects>
